# Dataset Configuration

dataset:
  name: "mnist". #Dataset
  num_classes: 2   #Number of output classes for the task (2: even or odd)
  validation_split_ratio: 0.1  #Fraction of training data to use for validation (10%)
  random_seed: 42.  #Ensures reproducibility for data splits

paths:
  data_dir: "./data"    #Root directory to store raw or preprocessed data.
  train_dataset: "./data/train"   #Paths where preprocessed training and validation datasets are saved.
  val_dataset: "./data/val"

split:      #Specifies the proportion of the dataset for training, validation, and testing.
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

preprocessing:
  image_size: 224. #Resize all images to 224×224 pixels (suitable for ResNet-18)
  channels: 3. #Convert grayscale images to 3-channel RGB.
  normalize:    #Standardizes pixel values to match the pretrained model’s expected input.
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

model:
  pretrained_name: "microsoft/resnet-18"      #Pretrained model checkpoint to fine-tune.
  id2label:
    0: "even"
    1: "odd"              #Maps numerical labels to human-readable class names and vice versa
  label2id:      
    "even": 0
    "odd": 1

data_processing:
  batch_size: 32 #Number of samples processed per training step.

